name: gateway-service

services:
  gateway_service:
    build:
      context: ../app
      dockerfile: ../docker/Dockerfile
    container_name: gateway_service
    restart: unless-stopped
    depends_on:
      - postgres
      - migrations
    env_file:
      - .env
    ports:
      - "50051:50051"
