name: gateway-service

services:
  gateway_service:
    build:
      context: ../app
      dockerfile: ../docker/Dockerfile
    container_name: gateway_service
    restart: unless-stopped
    ports:
      - "8080:8080"
